<a href="https://colab.research.google.com/github/21Ovi/TensorFlow_/blob/main/TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Fundamentals Exercises

In [1]:
import tensorflow as tf
import numpy as np

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [2]:
# Creating a Scalar
scalar = tf.constant(21)

# Creating a Vector
vector = tf.constant([21, 31])

# Creating a Matrix
matrix = tf.constant([[21, 31],
                      [31, 21]])

# Creating a Tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      
                      [[7, 8, 9],
                       [10, 11, 12]],
                      
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

2. Find the shape, rank and size of the tensors you created in 1.

In [3]:
# Getting shape
print( 'Shape: ',tensor.shape,'\n')

# Getting Rank
print( 'Rank: ',tf.rank(tensor),'\n')

# Getting Size
print( 'Size: ',tf.size(tensor))

Shape:  (3, 2, 3) 

Rank:  tf.Tensor(3, shape=(), dtype=int32) 

Size:  tf.Tensor(18, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [4]:
tensor1 = tf.random.uniform(
   shape=[5, 300],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.int32,
)

tensor2 = tf.random.uniform(
    shape=[5, 300],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.int32,
)

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [10]:
tf.reshape(tensor1, shape=(300, 5))
matrix_prod = tf.matmul(tensor1, tensor1)

InvalidArgumentError: ignored

5. Multiply the two tensors you created in 3 using dot product.

In [11]:
tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [19]:
tensor3D = tf.random.uniform(
    shape=(244, 244, 3),
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float16,
)

tensor3D

<tf.Tensor: shape=(244, 244, 3), dtype=float16, numpy=
array([[[0.7812 , 0.4033 , 0.831  ],
        [0.02832, 0.8584 , 0.421  ],
        [0.2695 , 0.1758 , 0.6855 ],
        ...,
        [0.1631 , 0.7734 , 0.8    ],
        [0.506  , 0.949  , 0.2812 ],
        [0.6875 , 0.1914 , 0.1172 ]],

       [[0.03613, 0.6904 , 0.4111 ],
        [0.833  , 0.6523 , 0.2471 ],
        [0.6377 , 0.46   , 0.536  ],
        ...,
        [0.1406 , 0.498  , 0.6826 ],
        [0.1963 , 0.4277 , 0.4014 ],
        [0.378  , 0.5684 , 0.126  ]],

       [[0.03223, 0.2686 , 0.915  ],
        [0.99   , 0.4844 , 0.925  ],
        [0.996  , 0.378  , 0.702  ],
        ...,
        [0.802  , 0.4834 , 0.29   ],
        [0.1211 , 0.254  , 0.4414 ],
        [0.4365 , 0.3613 , 0.2041 ]],

       ...,

       [[0.0957 , 0.7656 , 0.7793 ],
        [0.2324 , 0.2764 , 0.658  ],
        [0.745  , 0.62   , 0.616  ],
        ...,
        [0.1465 , 0.547  , 0.06055],
        [0.2266 , 0.8105 , 0.126  ],
        [0.0381 , 0.589

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [20]:
max = tf.reduce_max(tensor3D)
min = tf.reduce_min(tensor3D)

print("max value is :", max ,"\n")
print("min value is :", min)

max value is : tf.Tensor(0.999, shape=(), dtype=float16) 

min value is : tf.Tensor(0.0, shape=(), dtype=float16)


8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [23]:
tensor4D = tf.random.uniform(
    shape=(1, 224, 224, 3)
)

squeezedTensor = tf.squeeze(tensor4D)
squeezedTensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.28847134, 0.10128903, 0.9334878 ],
        [0.57462144, 0.24543393, 0.27564907],
        [0.68776333, 0.12025476, 0.3684107 ],
        ...,
        [0.99799585, 0.10281229, 0.09656072],
        [0.873258  , 0.07790732, 0.26249075],
        [0.36061847, 0.5988513 , 0.93927526]],

       [[0.87041926, 0.12167537, 0.6850798 ],
        [0.6389111 , 0.22552764, 0.9842632 ],
        [0.3225118 , 0.8599168 , 0.10901332],
        ...,
        [0.3432442 , 0.43206966, 0.9613621 ],
        [0.7161474 , 0.40818667, 0.14115262],
        [0.45185542, 0.62193286, 0.01969588]],

       [[0.17436075, 0.95175016, 0.6836951 ],
        [0.39613342, 0.05182409, 0.31457496],
        [0.29139543, 0.10626876, 0.9307983 ],
        ...,
        [0.84587574, 0.60473645, 0.12768471],
        [0.28862786, 0.17529356, 0.30070972],
        [0.10867488, 0.86899567, 0.34000635]],

       ...,

       [[0.36490273, 0.4467038 , 0.5246589 ],
        [0.16

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [45]:
indices = tf.constant([1, 2, 3,4 ,5 ,6 ,7 ,8 ,9 ,10])
indices

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

10. One-hot encode the tensor you created in 9.

In [46]:
tf.one_hot(indices, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>