<a href="https://colab.research.google.com/github/21Ovi/TensorFlow_/blob/main/TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Fundamentals Exercises

In [1]:
import tensorflow as tf
import numpy as np

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [2]:
# Creating a Scalar
scalar = tf.constant(21)

# Creating a Vector
vector = tf.constant([21, 31])

# Creating a Matrix
matrix = tf.constant([[21, 31],
                      [31, 21]])

# Creating a Tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      
                      [[7, 8, 9],
                       [10, 11, 12]],
                      
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

2. Find the shape, rank and size of the tensors you created in 1.

In [3]:
# Getting shape
print( 'Shape: ',tensor.shape,'\n')

# Getting Rank
print( 'Rank: ',tf.rank(tensor),'\n')

# Getting Size
print( 'Size: ',tf.size(tensor))

Shape:  (3, 2, 3) 

Rank:  tf.Tensor(3, shape=(), dtype=int32) 

Size:  tf.Tensor(18, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [4]:
tensor1 = tf.random.uniform(
   shape=[5, 300],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.int32,
)

tensor2 = tf.random.uniform(
    shape=[5, 300],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.int32,
)

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [10]:
tf.reshape(tensor1, shape=(300, 5))
matrix_prod = tf.matmul(tensor1, tensor1)

InvalidArgumentError: ignored

5. Multiply the two tensors you created in 3 using dot product.

In [11]:
tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [12]:
tensor3D = tf.random.uniform(
    shape=(244, 244, 3),
    minval=0,
    maxval=1
)

tensor3D

<tf.Tensor: shape=(244, 244, 3), dtype=float32, numpy=
array([[[0.37005293, 0.9572834 , 0.5666293 ],
        [0.41058362, 0.29749453, 0.41003323],
        [0.63072217, 0.270617  , 0.9966551 ],
        ...,
        [0.3866539 , 0.2260611 , 0.28329492],
        [0.48332906, 0.527737  , 0.6485405 ],
        [0.10931253, 0.26282823, 0.8035594 ]],

       [[0.9176141 , 0.7507912 , 0.5309876 ],
        [0.9819226 , 0.2704637 , 0.09369516],
        [0.7763878 , 0.62363017, 0.8016881 ],
        ...,
        [0.64171934, 0.0790844 , 0.89053154],
        [0.29825544, 0.8737738 , 0.6880189 ],
        [0.87361956, 0.62494636, 0.2340759 ]],

       [[0.9765581 , 0.01827455, 0.6914859 ],
        [0.48732722, 0.6987883 , 0.11175346],
        [0.44656408, 0.7017698 , 0.9925668 ],
        ...,
        [0.7231469 , 0.24660885, 0.43943906],
        [0.8618566 , 0.16253519, 0.21529984],
        [0.21430409, 0.00739765, 0.96485627]],

       ...,

       [[0.44555616, 0.5185274 , 0.500345  ],
        [0.14

7. Find the min and max values of the tensor you created in 6 along the first axis.

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

10. One-hot encode the tensor you created in 9.